# This file was generated by GoReleaser. DO NOT EDIT.
cask "cerebro" do
  version "1.9.0"

  on_macos do
    on_intel do
      sha256 "4ddbf1042d0d463d9758eca732eed5386d8936ad705738383fa15270c7a0199b"
      url "https://github.com/coetzeevs/cerebro/releases/download/v#{version}/cerebro_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0620fc2a72d4ac1f816757c1ff0b0d04c9505d89b6bf7af843caa6e5fbbcc510"
      url "https://github.com/coetzeevs/cerebro/releases/download/v#{version}/cerebro_#{version}_darwin_arm64.tar.gz"
    end
  end

  name "cerebro"
  desc "Local-first persistent memory system for AI agents"
  homepage "https://github.com/coetzeevs/cerebro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cerebro"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cerebro"]
  end

  # No zap stanza required

end
