# This file was generated by GoReleaser. DO NOT EDIT.
cask "cerebro" do
  version "1.5.1"

  on_macos do
    on_intel do
      url "https://github.com/coetzeevs/cerebro/releases/download/v#{version}/cerebro_#{version}_darwin_amd64.tar.gz"
      sha256 "0f043d2a4a82fdf7305dff8082384334dc87c39780da2942d73324dc2f088001"
    end
    on_arm do
      url "https://github.com/coetzeevs/cerebro/releases/download/v#{version}/cerebro_#{version}_darwin_arm64.tar.gz"
      sha256 "f001ca5d93f0f7b3a68bea30f9c4e147a2aa2ec2843aab6eee7d8afbd72c2dd3"
    end
  end

  name "cerebro"
  desc "Local-first persistent memory system for AI agents"
  homepage "https://github.com/coetzeevs/cerebro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cerebro"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cerebro"]
  end

  # No zap stanza required

end
