# This file was generated by GoReleaser. DO NOT EDIT.
cask "cerebro" do
  version "3.3.0"

  on_macos do
    on_arm do
      sha256 "f1d7eca9307cbdf79f0e88a9840c9507f2e2c754dc6a20a3e7c4b8f5e48895f7"
      url "https://github.com/coetzeevs/cerebro/releases/download/v#{version}/cerebro_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "1fae8888d9acf9ae76d12d5c8bae52f2742d8f40a09276fff439d819ac335207"
      url "https://github.com/coetzeevs/cerebro/releases/download/v#{version}/cerebro_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "cerebro"
  desc "Local-first persistent memory system for AI agents"
  homepage "https://github.com/coetzeevs/cerebro"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cerebro"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/cerebro"]
  end

  # No zap stanza required
end
